### ISSUE TITLE
Failures with GCC10

### ISSUE THREAD

**Issue by demerphq** [zeevt/csnappy#36]
The Sereal project is seeing consistent errors with csnappy when built with GCC 10.  When compiling with gcc 9 or earlier all tests pass, when building with GCC 10 multiple users are reporting tests showing corrupted data.

At this time I do not have a gcc 10 to replicate, I am working on it, but I thought I should file a report early.

Note the code *compiles* fine on gcc10 it just fails tests. Which is a bit worrisome, and suggests a compiler bug to me.

Yves

**Comment by soig** [comment]
I confirm we're quite a lot of people to hit this issue

**Comment by demerphq** [comment]
On Fri, 10 Jul 2020 at 04:36, soig <notifications@github.com> wrote:

> I confirm we're quite a lot of people to hit this issue
>
I have not been able to get a gcc10 built, my laptop linux is too old and I
havent had the time to upgrade it yet.

So I  have not been able to dig into this further directly personally.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by pterjan** [comment]
After further investigation, this happens when compiling IncrementalCopyFastPath with -O3

Reported to GCC at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96326

**Comment by demerphq** [comment]
I pushed a possible fix:

https://github.com/zeevt/csnappy/pull/37

**Comment by zt-initech** [comment]
Sereal bug: https://github.com/Sereal/Sereal/issues/229

**Comment by zeevt** [comment]
Sereal ticket: https://github.com/Sereal/Sereal/issues/229

Thank you for the investigation and the patch!

I've added a test that catches this issue in the unpatched version.

This project is not well maintained.

In the years since I forked this code from the original Google snappy project, the original Google snappy project has fixed this issue (a long time ago), and also did performance work that probably makes their current code faster than this code.

I recommend people use the code from the Google snappy project if they can.

I also recommend people use lz4 instead of snappy format, it should be better. Of course, it's not always possible to convert existing data.

**Comment by demerphq** [comment]
On Tue, 4 Aug 2020 at 03:23, zeevt <notifications@github.com> wrote:

> Sereal ticket: Sereal/Sereal#229
> <https://github.com/Sereal/Sereal/issues/229>
>
> Thank you for the investigation and the patch!
>
Pascal did a great job on that, thanks Pascal.

> I've added a test that catches this issue in the unpatched version.
>
> This project is not well maintained.
>
> In the years since I forked this code from the original Google snappy
> project, the original Google snappy project has fixed this issue (a long
> time ago), and also did performance work that probably makes their current
> code faster than this code.
>
> I recommend people use the code from the Google snappy project if they can.
>
I only maintain this part of the code, I didn't set up the dependencies,
and I'm a little out of my comfort zone on migrating away from your version
but ill see what I can do to migrate Sereal away. If you felt like
providing some guidance it would be welcome. :-)

FWIW, Sereal has now grown to support Zstd, Zlib and Snappy. Sigh. And the
folks that added the support for all three no longer actively work on
Sereal. :-)

Cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"
